version: '3'
services:
#  nginx-proxy:
#    image: jwilder/nginx-proxy 
#    restart: always
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - /var/run/docker.sock:/tmp/docker.sock:ro
#      - /root/.server/nginx-ssl/certs:/etc/nginx/certs:ro
#      - /root/.server/nginx-ssl/certs
#      - /etc/nginx/vhost.d
#      - /usr/share/nginx/html
#    labels:
#      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy 

  #letsencrypt:
  #  image: linuxserver/letsencrypt
  #restart: always
  #  volumes:
  #    - /root/.server/nginx-ssl/certs:/etc/nginx/certs:rw
  #    - /var/run/docker.sock:/var/run/docker.sock:ro
  #  volumes_from:
  #    - nginx-proxy:rw
  #  environment:
  #     - DEFAULT_EMAIL=ferna2909@hotmail.com
  
  #www1:
  #  image: nginx
  #  restart: always
  #  expose:
  #    - "80"
  #  volumes:
  #    - /root/.server/docker-share/html1/production:/usr/share/nginx/html:ro
  #      #- /root/.server/docker-share/html1/maintenance:/usr/share/nginx/html:ro
  #  environment:
  #    - VIRTUAL_HOST=ecommerce.matanga.net.ar
  #    - LETSENCRYPT_HOST=ecommerce.matanga.net.ar
  #    - LETSENCRYPT_EMAIL=ferna2909@hotmail.com

  #www2:
  #  image: nginx
  #  restart: always
  #  expose:
  #    - "80"
  #  volumes:
  #    - /root/.server/docker-share/html2/production:/usr/share/nginx/html:ro
  #      #- /root/.server/docker-share/html2/maintenance:/usr/share/nginx/html:ro
  #  environment:
  #    - VIRTUAL_HOST=dolarhoy.matanga.net.ar
  #    - LETSENCRYPT_HOST=dolarhoy.matanga.net.ar
  #    - LETSENCRYPT_EMAIL=ferna2909@hotmail.com

  #www3:
  #  image: nginx
  #  restart: always
  #  expose:
  #    - "80"
  #  volumes:
  #    - /root/.server/docker-share/html3/uade-29-abril-2020/ejercitacion_timer:/usr/share/nginx/html:ro
  #    #- /root/.server/docker-share/html3/uade-24-abril-2020:/usr/share/nginx/html:ro
  #  environment:
  #    - VIRTUAL_HOST=timer.matanga.net.ar
  #    - LETSENCRYPT_HOST=timer.matanga.net.ar
  #    - LETSENCRYPT_EMAIL=ferna2909@hotmail.com
      
  #www4:
  #  image: nginx
  #  restart: always
  #  expose:
  #    - "80"
  #  volumes:
  #    - /root/.server/docker-share/html3/uade-08-mayo-2020/ejercitacion_reloj:/usr/share/nginx/html:ro
  #    #- /root/.server/docker-share/html3/uade-24-abril-2020:/usr/share/nginx/html:ro
  #  environment:
  #    - VIRTUAL_HOST=reloj.matanga.net.ar
  #    - LETSENCRYPT_HOST=reloj.matanga.net.ar
  #    - LETSENCRYPT_EMAIL=ferna2909@hotmail.com 

  #www5:
  #  image: nginx
  #  restart: always
  #  expose:
  #    - "80"
  #  volumes:
  #    - /root/.server/docker-share/html3/uade-29-abril-2020/ejercitacion_calculadora:/usr/share/nginx/html:ro
  #    #- /root/.server/docker-share/html3/uade-24-abril-2020:/usr/share/nginx/html:ro
  #  environment:
  #    - VIRTUAL_HOST=calculadora.matanga.net.ar
  #    - LETSENCRYPT_HOST=calculadora.matanga.net.ar
  #    - LETSENCRYPT_EMAIL=ferna2909@hotmail.com

  #www6:
  #  image: nginx
  #  restart: always
  #  expose:
  #    - "80"
  #  volumes:
  #    - /root/.server/docker-share/html3/uade-15-mayo-2020/ejercitacion_tateti:/usr/share/nginx/html:ro
  #    #- /root/.server/docker-share/html3/uade-24-abril-2020:/usr/share/nginx/html:ro
  #  environment:
  #    - VIRTUAL_HOST=tateti.matanga.net.ar
  #    - LETSENCRYPT_HOST=tateti.matanga.net.ar
  #    - LETSENCRYPT_EMAIL=ferna2909@hotmail.com

  #www7:
  #  image: nginx
  #  restart: always
  #  expose:
  #    - "80"
  #  volumes:
  #    - /root/.server/docker-share/html3/uade-15-mayo-2020/ejercitacion_primos:/usr/share/nginx/html:ro
  #    #- /root/.server/docker-share/html3/uade-24-abril-2020:/usr/share/nginx/html:ro
  #  environment:
  #    - VIRTUAL_HOST=primos.matanga.net.ar
  #    - LETSENCRYPT_HOST=primos.matanga.net.ar
  #    - LETSENCRYPT_EMAIL=ferna2909@hotmail.com

# pagina del proyecto final de aude
  uade_frontend:
    image: nginx
    hostname: uade_frontend
    container_name: uade_frontend
    restart: always
    expose:
      - "80"
    volumes:
      - /root/.server/docker-share/html4:/usr/share/nginx/html:ro
      #- /root/.server/docker-share/html3/uade-24-abril-2020:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=whales.matanga.net.ar
      #- LETSENCRYPT_HOST=whales.matanga.net.ar
      #- LETSENCRYPT_EMAIL=ferna2909@hotmail.com
    networks:
      uade_tp_network:
        aliases:
          - uade_frontend
    
  uade_mysql_db:
    image: mysql:latest
    hostname: uade_mysql_db
    container_name: uade_mysql_db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /root/.server/mysql_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD='uade'
      - MYSQL_USER='test'
      - MYSQL_PASS='uade'
    networks:
      uade_tp_network:
        aliases:
          - uade_mysql_db
 
networks:
  uade_tp_network:
    external:
      name: pensaenverde
    #external: true
    #driver: bridge

 #######################
