nginx-proxy:
  image: jwilder/nginx-proxy 
  restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /root/.server//nginx-ssl/certs:/etc/nginx/certs:ro
    - /root/.server/nginx-ssl/certs
    - /etc/nginx/vhost.d
    - /usr/share/nginx/html
  labels:
    - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy 

letsencrypt:
  image: linuxserver/letsencrypt
  restart: always
  volumes:
    - /root/.server/nginx-ssl/certs:/etc/nginx/certs:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro
  volumes_from:
    - nginx-proxy:rw
  environment:
     - DEFAULT_EMAIL=ferna2909@hotmail.com

www1:
  image: nginx
  restart: always
  expose:
    - "80"
  volumes:
    - /root/.server/docker-share/html1/production:/usr/share/nginx/html:ro
      #- /root/.server/docker-share/html1/maintenance:/usr/share/nginx/html:ro
  environment:
    - VIRTUAL_HOST=ecommerce.matanga.net.ar
    - LETSENCRYPT_HOST=ecommerce.matanga.net.ar
    - LETSENCRYPT_EMAIL=ferna2909@hotmail.com

www2:
  image: nginx
  restart: always
  expose:
    - "80"
  volumes:
    - /root/.server/docker-share/html2/production:/usr/share/nginx/html:ro
      #- /root/.server/docker-share/html2/maintenance:/usr/share/nginx/html:ro
  environment:
    - VIRTUAL_HOST=dolarhoy.matanga.net.ar
    - LETSENCRYPT_HOST=dolarhoy.matanga.net.ar
    - LETSENCRYPT_EMAIL=ferna2909@hotmail.com

www3:
  image: nginx
  restart: always
  expose:
    - "80"
  volumes:
    - /root/.server/docker-share/html3/uade-29-abril-2020/ejercitacion_timer:/usr/share/nginx/html:ro
    #- /root/.server/docker-share/html3/uade-24-abril-2020:/usr/share/nginx/html:ro
  environment:
    - VIRTUAL_HOST=timer.matanga.net.ar
    - LETSENCRYPT_HOST=timer.matanga.net.ar
    - LETSENCRYPT_EMAIL=ferna2909@hotmail.com
 
www4:
  image: nginx
  restart: always
  expose:
    - "80"
  volumes:
    - /root/.server/docker-share/html3/uade-08-mayo-2020/ejercitacion_reloj:/usr/share/nginx/html:ro
    #- /root/.server/docker-share/html3/uade-24-abril-2020:/usr/share/nginx/html:ro
  environment:
    - VIRTUAL_HOST=reloj.matanga.net.ar
    - LETSENCRYPT_HOST=reloj.matanga.net.ar
    - LETSENCRYPT_EMAIL=ferna2909@hotmail.com 
